export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const ADJUST_ITEM_QUANTITY = "ADJUST_ITEM_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
